name: catalog-pokemon
services:
- name: web
  source_dir: /
  github:
    repo: yourusername/catalog-pokemon
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"